version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - <Your volume mapped":/var/lib/postgres
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    volumes:
      - <Your pgadmin mapped>:/var/
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@email.com"
      PGADMIN_DEFAULT_PASSWORD: "example"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
